import { db } from "@workspace/db";
import {
  racesTable,
  classesTable,
  backgroundsTable,
  spellsTable,
  itemsTable,
  type InsertBackground,
  type InsertSpell,
  type InsertItem,
} from "@workspace/db";

// ──────────────────────────────── RACES ────────────────────────────────
const RACES = [
  {
    slug: "human",
    name: "Human",
    description: "Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds.",
    abilityBonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 },
    traits: ["Extra Language", "Extra Feat (Variant)"],
    speed: 30,
    size: "Medium",
    languages: ["Common"],
    rawData: { subraces: [] },
  },
  {
    slug: "elf",
    name: "Elf",
    description: "Elves are a magical people of otherworldly grace, living in places of ethereal beauty.",
    abilityBonuses: { dexterity: 2 },
    traits: ["Darkvision", "Fey Ancestry", "Trance", "Keen Senses"],
    speed: 30,
    size: "Medium",
    darkvision: 60,
    languages: ["Common", "Elvish"],
    rawData: { subraces: ["High Elf", "Wood Elf", "Dark Elf (Drow)"] },
  },
  {
    slug: "dwarf",
    name: "Dwarf",
    description: "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.",
    abilityBonuses: { constitution: 2 },
    traits: ["Darkvision", "Dwarven Resilience", "Stonecunning", "Combat Training"],
    speed: 25,
    size: "Medium",
    darkvision: 60,
    languages: ["Common", "Dwarvish"],
    rawData: { subraces: ["Hill Dwarf", "Mountain Dwarf"] },
  },
  {
    slug: "halfling",
    name: "Halfling",
    description: "The comforts of home are the goals of most halflings' lives.",
    abilityBonuses: { dexterity: 2 },
    traits: ["Lucky", "Brave", "Halfling Nimbleness"],
    speed: 25,
    size: "Small",
    languages: ["Common", "Halfling"],
    rawData: { subraces: ["Lightfoot", "Stout"] },
  },
  {
    slug: "gnome",
    name: "Gnome",
    description: "A gnome's energy and enthusiasm for living shines through every inch of his or her tiny body.",
    abilityBonuses: { intelligence: 2 },
    traits: ["Darkvision", "Gnome Cunning"],
    speed: 25,
    size: "Small",
    darkvision: 60,
    languages: ["Common", "Gnomish"],
    rawData: { subraces: ["Forest Gnome", "Rock Gnome"] },
  },
  {
    slug: "half-elf",
    name: "Half-Elf",
    description: "Walking in two worlds but truly belonging to neither, half-elves combine what some say are the best qualities of their elf and human parents.",
    abilityBonuses: { charisma: 2 },
    traits: ["Darkvision", "Fey Ancestry", "Skill Versatility"],
    speed: 30,
    size: "Medium",
    darkvision: 60,
    languages: ["Common", "Elvish"],
    rawData: { subraces: [], extraAbilityBonus: "Two ability scores of player's choice +1" },
  },
  {
    slug: "half-orc",
    name: "Half-Orc",
    description: "Half-orcs are viewed with suspicion, but their toughness and ferocity are unmatched.",
    abilityBonuses: { strength: 2, constitution: 1 },
    traits: ["Darkvision", "Menacing", "Relentless Endurance", "Savage Attacks"],
    speed: 30,
    size: "Medium",
    darkvision: 60,
    languages: ["Common", "Orc"],
    rawData: { subraces: [] },
  },
  {
    slug: "tiefling",
    name: "Tiefling",
    description: "Tieflings are derived from human bloodlines. Their infernal heritage has left a clear imprint on their appearance.",
    abilityBonuses: { intelligence: 1, charisma: 2 },
    traits: ["Darkvision", "Hellish Resistance", "Infernal Legacy"],
    speed: 30,
    size: "Medium",
    darkvision: 60,
    languages: ["Common", "Infernal"],
    rawData: { subraces: [] },
  },
  {
    slug: "dragonborn",
    name: "Dragonborn",
    description: "Born of dragons, the dragonborn walk proudly through a world that greets them with fearful incomprehension.",
    abilityBonuses: { strength: 2, charisma: 1 },
    traits: ["Breath Weapon", "Damage Resistance", "Draconic Ancestry"],
    speed: 30,
    size: "Medium",
    languages: ["Common", "Draconic"],
    rawData: { subraces: [], dragonTypes: ["Black", "Blue", "Brass", "Bronze", "Copper", "Gold", "Green", "Red", "Silver", "White"] },
  },
];

// ──────────────────────────────── CLASSES ────────────────────────────────
const CLASSES = [
  {
    slug: "barbarian",
    name: "Barbarian",
    description: "A fierce warrior of primitive background who can enter a battle rage.",
    hitDie: 12,
    primaryAbility: "strength",
    savingThrows: ["strength", "constitution"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    toolProficiencies: [],
    skillChoices: { options: ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"], count: 2 },
    startingEquipment: ["Greataxe or martial melee weapon", "Two handaxes or simple weapon", "Explorer's pack", "4 javelins"],
    features: { "1": ["Rage", "Unarmored Defense"], "2": ["Reckless Attack", "Danger Sense"], "3": ["Primal Path"], "4": ["Ability Score Improvement"], "5": ["Extra Attack", "Fast Movement"] },
    spellcasting: {},
  },
  {
    slug: "bard",
    name: "Bard",
    description: "An inspiring magician whose power echoes the music of creation.",
    hitDie: 8,
    primaryAbility: "charisma",
    savingThrows: ["dexterity", "charisma"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    toolProficiencies: ["Three musical instruments"],
    skillChoices: { options: ["Any"], count: 3 },
    startingEquipment: ["Rapier or longsword or simple weapon", "Diplomat's or entertainer's pack", "Lute or musical instrument", "Leather armor", "Dagger"],
    features: { "1": ["Spellcasting", "Bardic Inspiration (d6)"], "2": ["Jack of All Trades", "Song of Rest (d6)"], "3": ["Expertise", "Bard College"], "4": ["Ability Score Improvement"], "5": ["Bardic Inspiration (d8)", "Font of Inspiration"] },
    spellcasting: { ability: "charisma", type: "known" },
  },
  {
    slug: "cleric",
    name: "Cleric",
    description: "A priestly champion who wields divine magic in service of a higher power.",
    hitDie: 8,
    primaryAbility: "wisdom",
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple"],
    toolProficiencies: [],
    skillChoices: { options: ["History", "Insight", "Medicine", "Persuasion", "Religion"], count: 2 },
    startingEquipment: ["Mace or warhammer", "Scale mail or leather armor or chain mail", "Light crossbow and 20 bolts or simple weapon", "Priest's pack or explorer's pack", "Shield and holy symbol"],
    features: { "1": ["Spellcasting", "Divine Domain"], "2": ["Channel Divinity (1/rest)", "Divine Domain Feature"], "3": [], "4": ["Ability Score Improvement"], "5": ["Destroy Undead (CR 1/2)"] },
    spellcasting: { ability: "wisdom", type: "prepared" },
  },
  {
    slug: "druid",
    name: "Druid",
    description: "A priest of the Old Faith, wielding the powers of nature and adopting animal forms.",
    hitDie: 8,
    primaryAbility: "wisdom",
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: ["Light", "Medium", "Shields (non-metal)"],
    weaponProficiencies: ["Clubs", "Daggers", "Darts", "Javelins", "Maces", "Quarterstaffs", "Scimitars", "Sickles", "Slings", "Spears"],
    toolProficiencies: ["Herbalism Kit"],
    skillChoices: { options: ["Arcana", "Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Religion", "Survival"], count: 2 },
    startingEquipment: ["Wooden shield or simple weapon", "Scimitar or simple melee weapon", "Leather armor", "Explorer's pack", "Druidic focus"],
    features: { "1": ["Spellcasting", "Druidic"], "2": ["Wild Shape", "Druid Circle"], "3": [], "4": ["Wild Shape Improvement", "Ability Score Improvement"], "5": ["Wild Shape Improvement"] },
    spellcasting: { ability: "wisdom", type: "prepared" },
  },
  {
    slug: "fighter",
    name: "Fighter",
    description: "A master of martial combat, skilled with a variety of weapons and armor.",
    hitDie: 10,
    primaryAbility: "strength",
    savingThrows: ["strength", "constitution"],
    armorProficiencies: ["All Armor", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    toolProficiencies: [],
    skillChoices: { options: ["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"], count: 2 },
    startingEquipment: ["Chain mail or leather armor, longbow, and 20 arrows", "Martial weapon and shield or two martial weapons", "Light crossbow and 20 bolts or two handaxes", "Dungeoneer's or explorer's pack"],
    features: { "1": ["Fighting Style", "Second Wind"], "2": ["Action Surge (1/rest)"], "3": ["Martial Archetype"], "4": ["Ability Score Improvement"], "5": ["Extra Attack"] },
    spellcasting: {},
  },
  {
    slug: "monk",
    name: "Monk",
    description: "A master of martial arts, harnessing the power of the body in pursuit of physical and spiritual perfection.",
    hitDie: 8,
    primaryAbility: "dexterity",
    savingThrows: ["strength", "dexterity"],
    armorProficiencies: [],
    weaponProficiencies: ["Simple", "Shortswords"],
    toolProficiencies: ["Artisan's tools or musical instrument"],
    skillChoices: { options: ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"], count: 2 },
    startingEquipment: ["Shortsword or simple weapon", "Dungeoneer's pack or explorer's pack", "10 darts"],
    features: { "1": ["Unarmored Defense", "Martial Arts"], "2": ["Ki", "Unarmored Movement"], "3": ["Monastic Tradition", "Deflect Missiles"], "4": ["Ability Score Improvement", "Slow Fall"], "5": ["Extra Attack", "Stunning Strike"] },
    spellcasting: {},
  },
  {
    slug: "paladin",
    name: "Paladin",
    description: "A holy warrior bound to a sacred oath.",
    hitDie: 10,
    primaryAbility: "strength",
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["All Armor", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    toolProficiencies: [],
    skillChoices: { options: ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"], count: 2 },
    startingEquipment: ["Martial weapon and shield or two martial weapons", "Five javelins or simple melee weapon", "Priest's or explorer's pack", "Chain mail and holy symbol"],
    features: { "1": ["Divine Sense", "Lay on Hands"], "2": ["Fighting Style", "Spellcasting", "Divine Smite"], "3": ["Divine Health", "Sacred Oath"], "4": ["Ability Score Improvement"], "5": ["Extra Attack"] },
    spellcasting: { ability: "charisma", type: "prepared" },
  },
  {
    slug: "ranger",
    name: "Ranger",
    description: "A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization.",
    hitDie: 10,
    primaryAbility: "dexterity",
    savingThrows: ["strength", "dexterity"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    toolProficiencies: [],
    skillChoices: { options: ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"], count: 3 },
    startingEquipment: ["Scale mail or leather armor", "Two shortswords or two simple melee weapons", "Dungeoneer's pack or explorer's pack", "Longbow and 20 arrows"],
    features: { "1": ["Favored Enemy", "Natural Explorer"], "2": ["Fighting Style", "Spellcasting"], "3": ["Ranger Archetype", "Primeval Awareness"], "4": ["Ability Score Improvement"], "5": ["Extra Attack"] },
    spellcasting: { ability: "wisdom", type: "known" },
  },
  {
    slug: "rogue",
    name: "Rogue",
    description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies.",
    hitDie: 8,
    primaryAbility: "dexterity",
    savingThrows: ["dexterity", "intelligence"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    toolProficiencies: ["Thieves' tools"],
    skillChoices: { options: ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"], count: 4 },
    startingEquipment: ["Rapier or shortsword", "Shortbow and 20 arrows or shortsword", "Burglar's or dungeoneer's or explorer's pack", "Leather armor", "Two daggers", "Thieves' tools"],
    features: { "1": ["Expertise", "Sneak Attack", "Thieves' Cant"], "2": ["Cunning Action"], "3": ["Roguish Archetype"], "4": ["Ability Score Improvement"], "5": ["Uncanny Dodge"] },
    spellcasting: {},
  },
  {
    slug: "sorcerer",
    name: "Sorcerer",
    description: "A spellcaster who draws on inherent magic from a gift or bloodline.",
    hitDie: 6,
    primaryAbility: "charisma",
    savingThrows: ["constitution", "charisma"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    toolProficiencies: [],
    skillChoices: { options: ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"], count: 2 },
    startingEquipment: ["Light crossbow and 20 bolts or simple weapon", "Component pouch or arcane focus", "Dungeoneer's pack or explorer's pack", "Two daggers"],
    features: { "1": ["Spellcasting", "Sorcerous Origin"], "2": ["Font of Magic"], "3": ["Metamagic"], "4": ["Ability Score Improvement"], "5": ["Metamagic"] },
    spellcasting: { ability: "charisma", type: "known" },
  },
  {
    slug: "warlock",
    name: "Warlock",
    description: "A wielder of magic derived from a bargain with an extraplanar entity.",
    hitDie: 8,
    primaryAbility: "charisma",
    savingThrows: ["wisdom", "charisma"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple"],
    toolProficiencies: [],
    skillChoices: { options: ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"], count: 2 },
    startingEquipment: ["Light crossbow and 20 bolts or simple weapon", "Component pouch or arcane focus", "Scholar's or dungeoneer's pack", "Leather armor", "Simple weapon", "Two daggers"],
    features: { "1": ["Otherworldly Patron", "Pact Magic"], "2": ["Eldritch Invocations"], "3": ["Pact Boon"], "4": ["Ability Score Improvement"], "5": ["Eldritch Invocations"] },
    spellcasting: { ability: "charisma", type: "pact" },
  },
  {
    slug: "wizard",
    name: "Wizard",
    description: "A scholarly magic-user capable of manipulating the structures of reality.",
    hitDie: 6,
    primaryAbility: "intelligence",
    savingThrows: ["intelligence", "wisdom"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    toolProficiencies: [],
    skillChoices: { options: ["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"], count: 2 },
    startingEquipment: ["Quarterstaff or dagger", "Component pouch or arcane focus", "Scholar's or explorer's pack", "Spellbook"],
    features: { "1": ["Spellcasting", "Arcane Recovery"], "2": ["Arcane Tradition"], "3": [], "4": ["Ability Score Improvement"], "5": [] },
    spellcasting: { ability: "intelligence", type: "prepared" },
  },
];

// ──────────────────────────────── BACKGROUNDS ────────────────────────────────
const BACKGROUNDS: InsertBackground[] = [
  {
    slug: "acolyte",
    name: "Acolyte",
    description: "You have spent your life in the service of a temple to a specific god or pantheon of gods.",
    skillProficiencies: ["insight", "religion"],
    toolProficiencies: [],
    languages: ["Choose two"],
    equipment: ["Holy symbol", "Prayer book or prayer wheel", "5 sticks of incense", "Vestments", "Common clothes", "15 gp"],
    feature: { name: "Shelter of the Faithful", description: "You command the respect of those who share your faith, and can perform the religious ceremonies of your deity." },
    personalityTraits: ["I idolize a particular hero of my faith.", "I can find common ground between the fiercest enemies."],
    ideals: ["Tradition: the ancient traditions of worship must be preserved."],
    bonds: ["I would die to recover an ancient relic of my faith."],
    flaws: ["I am inflexible in my thinking."],
  },
  {
    slug: "criminal",
    name: "Criminal",
    description: "You are an experienced criminal with a history of breaking the law.",
    skillProficiencies: ["deception", "stealth"],
    toolProficiencies: ["Thieves' tools", "One gaming set"],
    languages: [],
    equipment: ["Crowbar", "Dark common clothes with hood", "15 gp"],
    feature: { name: "Criminal Contact", description: "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals." },
    personalityTraits: ["I always have a plan for what to do when things go wrong.", "I am always calm, no matter what the situation."],
    ideals: ["Honor: I don't steal from others in the trade."],
    bonds: ["I'm trying to pay off an old debt I owe to a generous benefactor."],
    flaws: ["When I see something valuable, I can't think of anything but how to steal it."],
  },
  {
    slug: "folk-hero",
    name: "Folk Hero",
    description: "You come from a humble social rank, but you are destined for so much more.",
    skillProficiencies: ["animalHandling", "survival"],
    toolProficiencies: ["One type of artisan's tools", "Vehicles (land)"],
    languages: [],
    equipment: ["Artisan's tools (one type)", "Shovel", "Iron pot", "Common clothes", "10 gp"],
    feature: { name: "Rustic Hospitality", description: "Since you come from the ranks of the common folk, you fit in among them with ease." },
    personalityTraits: ["I judge people by their actions, not their words.", "If someone is in trouble, I'm always ready to lend help."],
    ideals: ["Respect: People deserve to be treated with dignity and respect."],
    bonds: ["I protect those who cannot protect themselves."],
    flaws: ["I'm convinced of the significance of my destiny."],
  },
  {
    slug: "noble",
    name: "Noble",
    description: "You understand wealth, power, and privilege. You carry a noble title, and your family owns land.",
    skillProficiencies: ["history", "persuasion"],
    toolProficiencies: ["One type of gaming set"],
    languages: ["Choose one"],
    equipment: ["Fine clothes", "Signet ring", "Scroll of pedigree", "25 gp"],
    feature: { name: "Position of Privilege", description: "Thanks to your noble birth, people are inclined to think the best of you." },
    personalityTraits: ["My eloquent flattery makes everyone I talk to feel like the most wonderful person in the world.", "The common folk love me for my kindness and generosity."],
    ideals: ["Responsibility: It is my duty to respect the authority of those above me."],
    bonds: ["I will face any challenge to win the approval of my family."],
    flaws: ["I secretly believe that everyone is beneath me."],
  },
  {
    slug: "sage",
    name: "Sage",
    description: "You spent years learning the lore of the multiverse. You scoured manuscripts and conducted experiments.",
    skillProficiencies: ["arcana", "history"],
    toolProficiencies: [],
    languages: ["Choose two"],
    equipment: ["Bottle of black ink", "Quill", "Small knife", "Letter from dead colleague with questions never answered", "Common clothes", "10 gp"],
    feature: { name: "Researcher", description: "When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it." },
    personalityTraits: ["I use polysyllabic words that convey the impression of great erudition.", "I've read every book in the world's greatest libraries."],
    ideals: ["Knowledge: The path to power and self-improvement is through knowledge."],
    bonds: ["I have an ancient text that holds terrible secrets that must not fall into the wrong hands."],
    flaws: ["I am easily distracted by the promise of information."],
  },
  {
    slug: "soldier",
    name: "Soldier",
    description: "War has been your life for as long as you care to remember.",
    skillProficiencies: ["athletics", "intimidation"],
    toolProficiencies: ["One type of gaming set", "Vehicles (land)"],
    languages: [],
    equipment: ["Insignia of rank", "Trophy from fallen enemy", "Bone dice or deck of cards", "Common clothes", "10 gp"],
    feature: { name: "Military Rank", description: "You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority." },
    personalityTraits: ["I'm always polite and respectful.", "I'm haunted by memories of war. I wake up screaming."],
    ideals: ["Greater Good: Our lot is to lay down our lives in defense of others."],
    bonds: ["I fight for those who cannot fight for themselves."],
    flaws: ["I'd rather eat my armor than admit when I'm wrong."],
  },
];

// ──────────────────────────────── SPELLS ────────────────────────────────
const SPELLS: InsertSpell[] = [
  {
    slug: "fire-bolt",
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.",
    higherLevel: "This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
  },
  {
    slug: "magic-missile",
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 force damage to its target. The darts all strike simultaneously.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    damageType: "force",
  },
  {
    slug: "cure-wounds",
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.",
    ritual: false,
    concentration: false,
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    damageType: null,
  },
  {
    slug: "burning-hands",
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (15-foot cone)",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    saveType: "dexterity",
  },
  {
    slug: "charm-person",
    name: "Charm Person",
    level: 1,
    school: "Enchantment",
    castingTime: "1 action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "1 hour",
    description: "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw. On a failed save, it is charmed by you until the spell ends or until you or your companions do anything harmful to it.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
    ritual: false,
    concentration: false,
    classes: ["bard", "druid", "sorcerer", "warlock", "wizard"],
    damageType: null,
    saveType: "wisdom",
  },
  {
    slug: "fireball",
    name: "Fireball",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "150 feet",
    components: ["V", "S", "M"],
    duration: "Instantaneous",
    description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much on a successful one.",
    higherLevel: "When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    damageType: "fire",
    saveType: "dexterity",
  },
  {
    slug: "hold-person",
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    duration: "1 minute",
    description: "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw.",
    higherLevel: "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.",
    ritual: false,
    concentration: true,
    classes: ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"],
    damageType: null,
    saveType: "wisdom",
  },
  {
    slug: "invisibility",
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    duration: "1 hour",
    description: "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The spell ends for a target that attacks or casts a spell.",
    higherLevel: "When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
    ritual: false,
    concentration: true,
    classes: ["bard", "sorcerer", "warlock", "wizard"],
    damageType: null,
  },
  {
    slug: "detect-magic",
    name: "Detect Magic",
    level: 1,
    school: "Divination",
    castingTime: "1 action",
    range: "Self",
    components: ["V", "S"],
    duration: "10 minutes",
    description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic.",
    higherLevel: null,
    ritual: true,
    concentration: true,
    classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"],
    damageType: null,
  },
  {
    slug: "eldritch-blast",
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels.",
    higherLevel: "At 5th level: two beams. At 11th level: three beams. At 17th level: four beams.",
    ritual: false,
    concentration: false,
    classes: ["warlock"],
    damageType: "force",
  },
  {
    slug: "sacred-flame",
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.",
    higherLevel: "This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
    ritual: false,
    concentration: false,
    classes: ["cleric"],
    damageType: "radiant",
    saveType: "dexterity",
  },
  {
    slug: "mage-armor",
    name: "Mage Armor",
    level: 1,
    school: "Abjuration",
    castingTime: "1 action",
    range: "Touch",
    components: ["V", "S", "M"],
    duration: "8 hours",
    description: "You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it until the spell ends. The target's base AC becomes 13 + its Dexterity modifier.",
    higherLevel: null,
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    damageType: null,
  },
  {
    slug: "thunderwave",
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (15-foot cube)",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you.",
    higherLevel: "When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.",
    ritual: false,
    concentration: false,
    classes: ["bard", "druid", "sorcerer", "wizard"],
    damageType: "thunder",
    saveType: "constitution",
  },
  {
    slug: "polymorph",
    name: "Polymorph",
    level: 4,
    school: "Transmutation",
    castingTime: "1 action",
    range: "60 feet",
    components: ["V", "S", "M"],
    duration: "1 hour",
    description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The spell has no effect on a shapechanger or a creature with 0 hit points.",
    higherLevel: null,
    ritual: false,
    concentration: true,
    classes: ["bard", "druid", "sorcerer", "wizard"],
    damageType: null,
    saveType: "wisdom",
  },
  {
    slug: "counterspell",
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "60 feet",
    components: ["S"],
    duration: "Instantaneous",
    description: "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability.",
    higherLevel: "When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "warlock", "wizard"],
    damageType: null,
  },
];

// ──────────────────────────────── ITEMS ────────────────────────────────
const ITEMS: InsertItem[] = [
  {
    slug: "longsword",
    name: "Longsword",
    type: "weapon",
    rarity: "common",
    description: "A versatile martial weapon. 1d8 slashing (one-handed) or 1d10 slashing (two-handed).",
    weight: "3",
    cost: { amount: 15, currency: "gp" },
    damageRoll: "1d8",
    damageType: "slashing",
    properties: ["versatile"],
  },
  {
    slug: "shortsword",
    name: "Shortsword",
    type: "weapon",
    rarity: "common",
    description: "A finesse martial weapon. 1d6 piercing damage.",
    weight: "2",
    cost: { amount: 10, currency: "gp" },
    damageRoll: "1d6",
    damageType: "piercing",
    properties: ["finesse", "light"],
  },
  {
    slug: "dagger",
    name: "Dagger",
    type: "weapon",
    rarity: "common",
    description: "A finesse, light, thrown simple weapon. 1d4 piercing damage. Range 20/60 ft.",
    weight: "1",
    cost: { amount: 2, currency: "gp" },
    damageRoll: "1d4",
    damageType: "piercing",
    properties: ["finesse", "light", "thrown"],
  },
  {
    slug: "handaxe",
    name: "Handaxe",
    type: "weapon",
    rarity: "common",
    description: "A light, thrown simple weapon. 1d6 slashing damage. Range 20/60 ft.",
    weight: "2",
    cost: { amount: 5, currency: "gp" },
    damageRoll: "1d6",
    damageType: "slashing",
    properties: ["light", "thrown"],
  },
  {
    slug: "greataxe",
    name: "Greataxe",
    type: "weapon",
    rarity: "common",
    description: "A heavy, two-handed martial weapon. 1d12 slashing damage.",
    weight: "7",
    cost: { amount: 30, currency: "gp" },
    damageRoll: "1d12",
    damageType: "slashing",
    properties: ["heavy", "two-handed"],
  },
  {
    slug: "leather-armor",
    name: "Leather Armor",
    type: "armor",
    rarity: "common",
    description: "Light armor. Base AC 11 + Dex modifier.",
    weight: "10",
    cost: { amount: 10, currency: "gp" },
    armorClass: 11,
    properties: ["light-armor"],
  },
  {
    slug: "chain-mail",
    name: "Chain Mail",
    type: "armor",
    rarity: "common",
    description: "Heavy armor. AC 16. Disadvantage on Dexterity (Stealth) checks. Requires STR 13.",
    weight: "55",
    cost: { amount: 75, currency: "gp" },
    armorClass: 16,
    properties: ["heavy-armor", "stealth-disadvantage"],
  },
  {
    slug: "shield",
    name: "Shield",
    type: "armor",
    rarity: "common",
    description: "A shield. While equipped, adds +2 to your AC.",
    weight: "6",
    cost: { amount: 10, currency: "gp" },
    armorClass: 2,
    properties: ["shield"],
  },
  {
    slug: "healers-kit",
    name: "Healer's Kit",
    type: "adventuring-gear",
    rarity: "common",
    description: "A pouch of bandages and salves. You can use an action to stabilize a creature with 0 hit points without a Medicine check. Contains 10 uses.",
    weight: "3",
    cost: { amount: 5, currency: "gp" },
    properties: [],
    rawData: { uses: 10 },
  },
  {
    slug: "potion-of-healing",
    name: "Potion of Healing",
    type: "potion",
    rarity: "common",
    description: "You regain 2d4+2 hit points when you drink this potion.",
    weight: "0.5",
    cost: { amount: 50, currency: "gp" },
    properties: [],
  },
  {
    slug: "bag-of-holding",
    name: "Bag of Holding",
    type: "wondrous-item",
    rarity: "uncommon",
    description: "This bag's interior space is considerably larger than its outside dimensions. It can hold up to 500 pounds, not exceeding 64 cubic feet.",
    weight: "15",
    cost: { amount: 0, currency: "—" },
    requiresAttunement: false,
    properties: [],
  },
  {
    slug: "cloak-of-protection",
    name: "Cloak of Protection",
    type: "wondrous-item",
    rarity: "uncommon",
    description: "You gain a +1 bonus to AC and saving throws while you wear this cloak. Requires attunement.",
    weight: "1",
    cost: { amount: 0, currency: "—" },
    requiresAttunement: true,
    properties: [],
  },
  {
    slug: "rope-hempen",
    name: "Rope, Hempen (50 feet)",
    type: "adventuring-gear",
    rarity: "common",
    description: "Has 2 hit points and can be burst with a DC 17 Strength check.",
    weight: "10",
    cost: { amount: 1, currency: "gp" },
    properties: [],
  },
  {
    slug: "torch",
    name: "Torch",
    type: "adventuring-gear",
    rarity: "common",
    description: "A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet.",
    weight: "1",
    cost: { amount: 1, currency: "cp" },
    properties: [],
  },
  {
    slug: "thieves-tools",
    name: "Thieves' Tools",
    type: "tool",
    rarity: "common",
    description: "Includes a small file, lock picks, a small mirror on a metal handle, narrow-bladed scissors, and pliers. Used to disarm traps and pick locks.",
    weight: "1",
    cost: { amount: 25, currency: "gp" },
    properties: [],
  },
];

// ──────────────────────────────── SEED FUNCTION ────────────────────────────────
async function seed() {
  console.log("🌱 Seeding SRD data...");

  console.log("  Seeding races...");
  for (const race of RACES) {
    await db.insert(racesTable).values(race).onConflictDoUpdate({
      target: racesTable.slug,
      set: race,
    });
  }
  console.log(`  ✓ ${RACES.length} races seeded`);

  console.log("  Seeding classes...");
  for (const cls of CLASSES) {
    await db.insert(classesTable).values(cls).onConflictDoUpdate({
      target: classesTable.slug,
      set: cls,
    });
  }
  console.log(`  ✓ ${CLASSES.length} classes seeded`);

  console.log("  Seeding backgrounds...");
  for (const bg of BACKGROUNDS) {
    await db.insert(backgroundsTable).values(bg).onConflictDoUpdate({
      target: backgroundsTable.slug,
      set: bg,
    });
  }
  console.log(`  ✓ ${BACKGROUNDS.length} backgrounds seeded`);

  console.log("  Seeding spells...");
  for (const spell of SPELLS) {
    await db.insert(spellsTable).values(spell).onConflictDoUpdate({
      target: spellsTable.slug,
      set: spell,
    });
  }
  console.log(`  ✓ ${SPELLS.length} spells seeded`);

  console.log("  Seeding items...");
  for (const item of ITEMS) {
    await db.insert(itemsTable).values(item).onConflictDoUpdate({
      target: itemsTable.slug,
      set: item,
    });
  }
  console.log(`  ✓ ${ITEMS.length} items seeded`);

  console.log("✅ SRD seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
