// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/Adventurer.tsx": () => import("../components/mockups/landing/Adventurer.tsx"),
  "./components/mockups/landing/Quill.tsx": () => import("../components/mockups/landing/Quill.tsx"),
  "./components/mockups/landing/Tavern.tsx": () => import("../components/mockups/landing/Tavern.tsx")
};
